### ISSUE TITLE
shared-links.sql.retention: unknown unit d in duration 30d

### ISSUE THREAD

**Issue by rekup** [promlabs/promlens-public#12]
Starting promlens with the cli flag `--shared-links.sql.retention=30d` leads to the following error:

```bash
/ # /promlens --shared-links.sql.retention=30d
error parsing commandline arguments: time: unknown unit d in duration 30d
usage: promlens [<flags>]
...
```
I'm not sure whether this is a bug or maybe the documentation is just wrong:

```
      --shared-links.sql.retention=0  
                                 The maximum retention time for shared links when using a SQL
                                 database (e.g. '10m', '12h', '30d'). Set to 0 for infinite
                                 retention.
```
This issue occurs in promlens `v0.11.1`

**Comment by juliusv** [comment]
@rekup Oh thanks for pointing that out, and sorry about that! When writing the flag description I forgot that in Go, the built-in duration parsing only works up to the unit of hours (and smaller), but not days. I'll fix the docstring in the next release. To achieve the same effect, you would have to provide `--shared-links.sql.retention=720h`.

**Comment by juliusv** [comment]
Hi! There's great news today: PromLens is now fully open-source and has been migrated to the Prometheus project: https://twitter.com/juliusvolz/status/1584897156405940224

As part of that open-sourcing, this existing repository will no longer be used for tracking issues or creating any updates. Please feel free to open issues against the new repo as well, or perhaps even contribute changes (now that it's OSS!) :)

This issue should by the way be fixed in the new open-source release now, so closing it here.
