### ISSUE TITLE
Error validating server health: Failed to fetch

### ISSUE THREAD

**Issue by wymangr** [promlabs/promlens-public#18]
I was wondering how PrmLens handled communication to/from the Prometheus database. For example, in Grafana when you are setting up a Prometheus data source, there is an "Access" option. Server will have the browser forward the request to Grafana that will then communicate on the backend with Prometheus. Where Browser access will allow the browser to communicate directly to the data source. 

The reason I ask, is I have Prometheus in a docker container, but the ports only exposed within the backend docker network. Then I have a reverse proxy allowing access to it from outside the docker network, but adds authentication. When I try to access Prometheus using http://<containername>:9090 or https://<reverseproxy> I get the following error:

Error validating server health: Failed to fetch

My guess is that it's not able to validate the server health of the container url, because PromLens is setup with Browser access and my browser can't access Prometheus that way, only other containers on the same docker network can. And I'm guessing it doesn't work with the reverse proxy, because of the authentication, or maybe because I'm using a self signed certificate and it's "Not secure"?

My ask would be, if you are using browser access, to allow (like Grafana) a way to communicate with Prometheus on the backend through PromLens, or add some environment variables for username/password to authenticate to Prometheus. 

It could just be I'm doing something wrong and I don't know what I'm talking about? Lol

**Comment by juliusv** [comment]
Hi @wymangr, thanks for asking! The personal / free version of PromLens indeed only allows you to connect to an endpoint directly from the browser, and it also does not have more configurability in terms of auth etc.

When you apply a license key, there are more possibilities, but rather than try to reimplement all possible auth and proxying settings directly in PromLens, PromLens allows you to connect to Grafana (via an API token) in such a way that PromLens a) lists all datasources you have configured in Grafana, and b) proxy queries through the PromLens backend and Grafana to those datasources (PromLens frontend -> PromLens backend -> Grafana -> Prometheus), so this automatically inherits all the auth settings that you have for that datasource in Grafana. This assumes that you have the Grafana datasource set to proxy mode (vs. direct connection from the browser), which is the default these days.

You can see a bit of an architecture explanation about that here: https://github.com/promlabs/promlens-public#architecture

But basically this means that as long as you are already using Grafana and allow PromLens to connect to it, you should be able to use all of the Prometheus datasources in Grafana with it.

If that sounds interesting, we can chat about a (trial or full) license at julius.volz@promlabs.com :)

Or let me know if you have other questions about this!

**Comment by wymangr** [comment]
@juliusv, thanks for clarifying that for me. That makes perfect sense! I

**Comment by danfromtitan** [comment]
Came across this issue while running promlens in a k8s pod: I'd like the free version of promlens to proxy the queries to backend cortex's query-frontend (or any Prometheus API for that matter) so I can try some queries before I can decide whether I want to pay for Grafana integration. At the point where I am now I can't even tell whether promlens can run a query :)

For this use case, I gave promlens a URL like http://cortex-query-frontend.cortex.svc.cluster.local:8080/prometheus/api/v1/ - this should resolve locally in the k8s cluster to the cortex query service and promlens should return results in the browser where I kubectl port-forwarded the connection.

**Comment by juliusv** [comment]
@danfromtitan I'd be happy to send you a trial license key so you can try the proxying through Grafana, just use the "Get a 30-day trial license key" button on https://promlens.com/pricing/ :)

That said, you should be able to access your datasource without a license key hopefully (if you serve PromLens over HTTP and not HTTPS), but I guess your browser does not resolve your `*.cluster.local` address. If you used `kubectl port-forward` from your laptop / desktop, then wouldn't you want to enter `http://localhost:8080/prometheus/api/v1` as the Prometheus endpoint URL in PromLens instead? If that doesn't work, it would be interesting to know what the Console and Network tabs give you in terms of errors on the request.

**Comment by danfromtitan** [comment]
Yes, once I realised promlent won't proxy the request I tried localhost port forwarding to Cortex query backend, I keep getting "Failed to fetch". Would you be able to tell what's the check that fails (I don't seem to be able to find the sourcode anywhere to check for that myself) ?

**Comment by juliusv** [comment]
@danfromtitan Often unfortunately the browser doesn't hand a more detailed error to the Javascript level (so PromLens wouldn't be able to show more than "failed to fetch"), but e.g. in Chrome's DevTools inspector should show you the failure reason. Either you would see it in the "Network" tab for the failed request, or if the request was not even executed at all (e.g. when it violates certain browser security rules), you would see an error logged about the denied request in the "Console" tab.

**Comment by danfromtitan** [comment]
Thanks for pointing me in the right direction, I see PromLens makes an initial API request for labels. I fixed the localhost URI to be what Cortex backend expects http://localhost:8081/prometheus/ and I've also added ModHeader Chrome extension to set the X-Scope-OrgID auth header Cortex expects in the request. I can run queries now from PromLens against the backend Cortex querier service :)

**Comment by juliusv** [comment]
@danfromtitan Great! Yeah, and if you proxy queries through Grafana, you'll have to do fewer of those hacks :)
