### ISSUE TITLE
Parsed sub query evaluation doesn't seem to be passing provided time/offset

### ISSUE THREAD

**Issue by arajkumar** [promlabs/promlens-public#19]
I've a prometheus TSDB which is quite old. In order to perform queries, I usually make use of offset/time fields in the promlens UI. However for the subtree evaluation, the offset/time is not passed to the `/api/v1/query` endpoint and this leads to empty results.

<img width="1654" alt="Screenshot 2021-09-17 at 1 22 12 PM" src="https://user-images.githubusercontent.com/3874763/133746170-a8a74be9-339d-4022-8c3b-ca5a7292daef.png">

**Comment by juliusv** [comment]
Hi @arajkumar, thanks for your report! I assume you are not talking about the `offset` PromQL query construct, but only about the two UI input fields that you outlined in red, correct? In Prometheus, those indicate the overall end time of the graph range and the duration of the graph range (from which the start of the range is derived), and they are passed to the query API endpoint not as part of the PromQL expression (`query` parameter), but as separate HTTP parameters (`start` and `end`, as well as `step` for the resolution), e.g.:

![query](https://user-images.githubusercontent.com/538008/133751357-b6acd641-f6cc-4c27-8477-0b35914b8ea7.png)

You can see that the time range selection works for this query, compare for example https://demo.promlens.com/?l=pUvXCei2q4O and https://demo.promlens.com/?l=X0_zH0eBq7U for the same expression, with different end times, returning different data.

Could it be that something else is off in the selectors in your query so that they do not select any data at all?

**Comment by juliusv** [comment]
Hi @arajkumar, let me know in case you have more info on this, otherwise I think I'll have to close it as I'm unsure it is a problem in PromLens at the moment.

**Comment by juliusv** [comment]
Closing for now, let me know in case the problem persists, with some details regarding my comment above :)
