### ISSUE TITLE
FEAT: Option to ignore Grafana invalid certificate

### ISSUE THREAD

**Issue by RiRa12621** [promlabs/promlens-public#24]
Sometimes for rapid prototyping we will not have a valid certificate. An example for that is a local CRC cluster, that does expose Grafana but with a self-signed certitifcate.

Promlens should have an option to ignore certificate errors when connecting to grafana
![Screenshot 2022-03-18 at 09 46 07](https://user-images.githubusercontent.com/14996407/158966831-57c0cbaf-29a5-4ac4-a8a5-bf7ef9ca5785.png)
.

**Comment by juliusv** [comment]
Makes sense, will see if I can manage to add that for the next release. Thanks!

**Comment by juliusv** [comment]
Hi! There's great news today: PromLens is now fully open-source and has been migrated to the Prometheus project: https://twitter.com/juliusvolz/status/1584897156405940224

As part of that open-sourcing, this existing repository will no longer be used for tracking issues or creating any updates. Please feel free to open issues against the new repo as well, or perhaps even contribute changes (now that it's OSS!) :)

Unfortunately it is not possible to migrate issues between GitHub organizations, otherwise I would simply migrate this issue to the new location.
