### ISSUE TITLE
Shared Link data cleanup option

### ISSUE THREAD

**Issue by hartman17** [promlabs/promlens-public#6]
It would be nice if we could pass in a data retention flag to have shared links cleaned up based on days.   Maybe run a cleanup script to delete rows older than  X number of days every 24 hours. 

Example: --shared-links.sql.retention=90

**Comment by juliusv** [comment]
@hartman17 This is a great idea, thanks! Will look at implementing this for the next release. Maybe it also makes sense to build an index page showing all shared links (with option to delete links), although I'm not sure how useful it would be.

**Comment by hartman17** [comment]
Index page is interesting but would probably need a short description to explain what the query is for and what it is showing.   That way when you look at the index page you can see links and what the are used for.  So when you click on "share"  you could have a "short description" field be optional before generating the link?    

I think that would be helpful if you are working on a query, share it, then say you lost the link and can't find it in any IM client :)

**Comment by juliusv** [comment]
Exactly, that's why I was also thinking that the index page isn't too useful at the moment, without clearer description of the links. Although then at least you'd be able to quickly find a link again that you created a while ago. Since that's probably better discussed in a separate issue though, I created one here: https://github.com/promlabs/promlens-public/issues/7

**Comment by juliusv** [comment]
I'm currently looking into how to do this. It would be nice to avoid an additional tool / script to run, so I'm thinking of having a regularly scheduled background job in the main PromLens server. I may just start by adding this for SQL-based storage first, since GCS and other cloud object storage providers usually already have built-in lifecycle management features (e.g. regularly delete any objects older than a certain age): https://cloud.google.com/storage/docs/lifecycle

**Comment by juliusv** [comment]
For SQL shared links, this is implemented now: https://promlabs.com/blog/2020/12/15/showcasing-promlens-0.11.0#cleaning-up-old-shared-links

For GCS the recommendation is to simply do this using a bucket retention policy, so closing this for now.
